name: Create Issue from Form

on:
  repository_dispatch:
    types: [form-submission]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue from form
      uses: peter-evans/create-issue@v5
      with:
        token: ${{ secrets.GH_ISSUE_TOKEN }}
        title: "Game Night Signup - ${{ github.event.client_payload.name }}"
        body: |
          **Name:** ${{ github.event.client_payload.name }}
          **Nights Available:** ${{ github.event.client_payload.nights }}
          **Notes:** ${{ github.event.client_payload.notes }}
