name: Save Game Night Submissions

on:
  repository_dispatch:
    types: [form-submission]

jobs:
  append_entry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure data file exists
        run: |
          if [ ! -f submissions.json ]; then
            echo "[]" > submissions.json
          fi

      - name: Append to JSON
        run: |
          echo 'Appending submission...'
          cat submissions.json | jq ". + [${{ toJson(github.event.client_payload) }}]" > tmp.json
          mv tmp.json submissions.json

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add submissions.json
          git commit -m "📥 New game night submission"
          git push
