name: Save Game Night Submissions

on:
  repository_dispatch:
    types: [game-night-signup]

jobs:
  append_to_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Append data to CSV
      run: |
        echo "Saving new game night signup..."
        PAYLOAD="${{ toJSON(github.event.client_payload) }}"
        echo "$PAYLOAD" | jq -r '[.name, .nights, .timezone, .platforms, .subs, .free, .paid, .notes] | @csv' >> submissions.csv

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add submissions.csv
        git commit -m "📥 New game night submission"
        git push
